name: neurobridge_v1
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - scanpy
  - plink
  - pip:
      - polars
      - adjustText
      - cellxgene-census
